[book]
authors = ["Seasawher"]
language = "ja"
multilingual = false
src = "src"
title = "Xena 日本語訳"

[build]
create-missing = false
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/lean-ja/xena-ja"

# 日本語検索に対応していないため，無効にする
[output.html.search]
enable = false
